services:
  mibaraka-house:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mibaraka-house
    restart: unless-stopped
    ports:
      - "0.0.0.0:8083:80"
    volumes:
      - ./storage:/var/www/html/storage
      - .env:/var/www/html/.env
    networks:
      - shared-network
    # Note: On a supprimé "depends_on" car la BDD tourne déjà de manière globale

networks:
  shared-network:
    external: true